apps/stocks_info/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', TickerFormView.as_view(), name='home'),
    path('snp500_eq_weight', SnP500View.as_view(), name='snp500'),
    path('finviz_news', FinvizNews.as_view(), name='news'),
    path('check_ticker', TickerFormView.as_view(), name='check_ticker'),
    path('gaps', GapsView.as_view(), name='gaps'),
    path('aliases_main', AliasesMain.as_view(), name='aliases_main'),
    path('pandas_back_test', PandasDFStocks.as_view(), name='pandas_back_test'),
    path('breakout', BreakOutMorningRange.as_view(), name='breakout'),
    path('watchlist', HomeLeftFormView.as_view(), name='watchlist'),
    path('toolkit_facade', ToolkitFacadeServicesMain.as_view(), name='toolkit_facade'),
    path('aliases_service', AliasService.as_view(), name='aliases_service'),
    path('mailbox_service', MailboxService.as_view(), name='mailbox_service'),
    path('domain_service', DomainService.as_view(), name='domain_service'),
]

trading_advisor_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.stocks_info.urls')),
]

apps/stocks_info/models.py
from django.db import models
from django.urls import reverse


class AliasModel(models.Model):
    alias = models.EmailField(max_length=100)
    domain_name = models.CharField(max_length=100)
    mailbox = models.EmailField(max_length=100)
    new_alias = models.EmailField(max_length=100)
    old_alias = models.EmailField(max_length=100)

    class Meta:
        managed = False


class RTFModel(models.Model):
    is_enabled = models.BooleanField(default=False)
    local_part = models.CharField(max_length=100)
    new_domain_name = models.CharField(max_length=100)
    old_domain_name = models.CharField(max_length=100)
    is_trial = models.BooleanField(default=False)
    plan_id = models.IntegerField(default=0)
    user_name = models.CharField(max_length=100)
    digit = models.IntegerField(default=0)
    selector = models.CharField(max_length=100)
    private_key = models.CharField(max_length=100)
    public_key = models.CharField(max_length=100)
    new_password = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    quota = models.IntegerField(default=0)
    is_active = models.BooleanField(default=False)
    enabled = models.BooleanField(default=False)
    mx_record = models.CharField(max_length=100)
    home_dir = models.CharField(max_length=100)
    catch_all = models.BooleanField(default=False)
    active = models.BooleanField(default=False)
    alias = models.EmailField(max_length=100)
    domain_name = models.CharField(max_length=100)
    mailbox = models.EmailField(max_length=100)
    new_alias = models.EmailField(max_length=100)
    old_alias = models.EmailField(max_length=100)

    class Meta:
        managed = False


class WatchListModel(models.Model):
    ticker = models.CharField(max_length=100)
    pnl = models.CharField(max_length=100)
    winrate = models.CharField(max_length=100)
    timeframe = models.CharField(max_length=100)
    winloss = models.CharField(max_length=100)

    # def get_absolute_url(self):
    #     return reverse('breakout', kwargs={'pk': self.pk})

apps/stocks_info/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import AliasModel, WatchListModel


class TickerForm(forms.Form):
    ticker = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Enter ticker', 'class': 'form-control'})
    )


class GapsForm(forms.Form):
    ticker = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Enter ticker', 'class': 'form-control'})
    )

    gap = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Enter gap %', 'class': 'form-control'})
    )


class DeleteAliasForm(forms.Form):
    alias = forms.EmailField(
        label="",
        required=True,
        max_length=100,
        widget=forms.TextInput({"placeholder": "Enter alias", "class": "form-control"}),
    )


class GetAliasForm(forms.Form):
    mailbox = forms.EmailField(
        label="",
        required=True,
        max_length=100,
        widget=forms.TextInput({"placeholder": "Enter mailbox", "class": "form-control"}),
    )


class PandasBackTestForm(forms.Form):
    ticker = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Enter ticker', 'class': 'form-control'})
    )

    stop_loss = forms.FloatField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Enter stop-loss', 'class': 'form-control'})
    )

    take_profit = forms.FloatField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Enter take-profit', 'class': 'form-control'})
    )


class AliasForm(forms.ModelForm):

    class Meta:
        model = AliasModel
        fields = ['alias', 'domain_name', 'mailbox', 'mailbox', 'new_alias', 'old_alias']
        widgets = {
            'alias': forms.TextInput(attrs={'placeholder': 'Enter alias', 'class': 'form-control',}),
            'domain_name': forms.HiddenInput(attrs={'value': 'value',}),
            'mailbox': forms.TextInput(attrs={'placeholder': 'Enter mailbox', 'class': 'form-control',}),
            'new_alias': forms.TextInput(attrs={'placeholder': 'Enter new alias', 'class': 'form-control',}),
            'old_alias': forms.TextInput(attrs={'placeholder': 'Enter old alias', 'class': 'form-control',}),
        }


class GetAliasFormMode(AliasForm):
    AliasForm.Meta.fields = ['mailbox']
    method = forms.CharField(widget=forms.HiddenInput(), initial='get_mailbox_aliases')


class CreateAliasFormMode(AliasForm):
    AliasForm.Meta.fields = ['alias', 'domain_name', 'mailbox']
    method = forms.CharField(widget=forms.HiddenInput(), initial='create_mailbox_alias')


class UpdateAliasFormMode(AliasForm):
    AliasForm.Meta.fields = ['domain_name', 'mailbox', 'old_alias', 'new_alias']
    AliasForm.Meta.widgets['mailbox'] = forms.HiddenInput()
    method = forms.CharField(widget=forms.HiddenInput(), initial='update_mailbox_alias')


class DeleteAliasFormMode(AliasForm):
    AliasForm.Meta.fields = ['alias']
    method = forms.CharField(widget=forms.HiddenInput(), initial='delete_mailbox_alias')
    active_mailbox = forms.CharField(widget=forms.HiddenInput(), initial='')


class BreakOutRangeForm(forms.Form):
    ticker = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Enter ticker', 'class': 'form-control'})
    )

    tf = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Enter time-frame', 'class': 'form-control'})
    )

    period = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Enter period', 'class': 'form-control'})
    )

    profit = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Enter take-profit', 'class': 'form-control'})
    )


class WatchListForm(forms.ModelForm):

    class Meta:
        model = WatchListModel
        fields = '__all__'

        widgets = {
            'ticker': forms.TextInput(attrs={'placeholder': 'Enter ticker', 'class': 'form-control form-control-sm'}),
            'pnl': forms.TextInput(attrs={'placeholder': 'Enter PnL', 'class': 'form-control form-control-sm'}),
            'winrate': forms.TextInput(attrs={'placeholder': 'Enter Winrate', 'class': 'form-control form-control-sm'}),
            'timeframe': forms.TextInput(attrs={'placeholder': 'Enter Time Frame', 'class': 'form-control form-control-sm'}),
            'winloss': forms.TextInput(attrs={'placeholder': 'Enter Win Loss', 'class': 'form-control form-control-sm'}),
        }

    def clean_ticker(self):
        ticker = self.cleaned_data['ticker']
        if len(ticker) > 5:
            raise ValidationError('Ticker name length must be up to 5 symbols')

        return ticker

apps/stocks_info/templates/toolkit/aliases_main.html
{% extends "stocks_info/home.html" %}

{% block page %}
<!-- set jquery cdn -->
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous">
  </script>
{{form}}
<!-- Get Alias form -->
<div class="container">
  <div class="row">
    <div class="col col-md-6">
      <form method="post" class="form-inline .was-validated">
        {% csrf_token %}
        <div class="form-group pull-left get-aliases-form">
          {{ form.get_mailbox_aliases }}
          <button class="btn btn-primary get-aliases" type="submit">Get Aliases!</button>
        </div>
      </form>
    </div>
    <div class="col col-md-4">
    </div>
    <div class="col col-md-2">
      <button type="button" class="btn btn-primary end-0 pull-right create-alias" data-toggle="modal"
        data-target="#create-alias-modal">Create Alias!</button>
    </div>
  </div>
</div>

<!-- Create Alias form  -->
<!--<div class="modal fade" id="create-alias-modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="modalLabel-create">Create mailbox alias!</h4>
      </div>-->
      <form method="post">
        {% csrf_token %}
        <div class="modal-body">
          <div class="form-group create-alias-form">
            {{ form.create_mailbox_alias }}
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" type="submit">Create Alias!</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </form>
<!--
    </div>
  </div>
</div>-->


<!--{% if response %}
{% if response.result %}
<div class="container">
  {% if extra_data.method == "get_mailbox_aliases" %}
  <div class="row">
    <div class="col col-md-12">
      <h3>Aliases for <b>{{extra_data.mailbox}}</b></h3>
    </div>
  </div>
  <div class="row">
    <div class="col col-md-12">
      <table class="table table-striped border border-1 rounded-3 p-3 shadow p-3 mb-5 bg-body rounded">
        <thead>
          <tr>
            <th scope="col" class="col-md-2">Status</th>
            <th scope="col" class="col-md-2">Active</th>
            <th scope="col" class="col-md-4">Alias</th>
            <th scope="col" class="col-md-2"></th>
            <th scope="col" class="col-md-2"></th>
          </tr>
        </thead>
        <tbody>
          {% for row in response.result %}
          <tr>
            <td class="text-success"><strong>Success</strong></td>
            <td>{{row.Active}}</td>
            <td>{{row.Alias}}</td>
            <td><button type="button" alias="{{row.Alias}}" active_mailbox="{{extra_data.mailbox}}"
                class="btn btn-primary btn-sm update-alias" data-toggle="modal"
                data-target="#update-alias-modal">Update</button></td>
            <td><button type="button" alias="{{row.Alias}}" active_mailbox="{{extra_data.mailbox}}"
                class="btn btn-secondary btn-sm btn-danger delete-alias" data-toggle="modal"
                data-target="#delete-alias-modal">Delete</button></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
-->

  <!-- Update Alias form  -->
  <div class="modal fade" id="update-alias-modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="modalLabel-update">Update mailbox alias!</h4>
        </div>
        <form method="post">
          {% csrf_token %}
          <div class="modal-body">
            <div class="form-group update-alias-form">
              {{ form.update_mailbox_alias }}
            </div>
          </div>
          <div class="modal-footer">
            <button class="btn btn-primary" type="submit">Update Alias!</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <!-- Delete Alias form  -->
  <div class="modal fade" id="delete-alias-modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="modalLabel-delete">Delete mailbox alias!</h4>
        </div>
        <form method="post">
          {% csrf_token %}
          <div class="modal-body">
            <div class="form-group delete-alias-form">
              {{ form.delete_mailbox_alias }}
            </div>
          </div>
          <div class="modal-footer">
            <button class="btn btn-primary" type="submit">Delete Alias!</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </form>
      </div>
    </div>
  </div>
<!--
  {% endif %}-->

  <!-- Successfully create mailbox alias -->
  {% if extra_data.method == "create_mailbox_alias" %}
  <div class="row">
    <div class="col col-md-12">
      <h3>You have successfully created the alias <b>{{extra_data.cleaned_data.alias}}</b> for mailbox
        <b>{{extra_data.cleaned_data.mailbox}}</b></h3>
    </div>
  </div>
  {% endif %}

  <!-- Successfully update mailbox alias -->
  {% if extra_data.method == "update_mailbox_alias" %}
  <div class="row">
    <div class="col col-md-12">
      <h3>You have successfully updated the alias <b>{{extra_data.cleaned_data.old_alias}}</b> to
        <b>{{extra_data.cleaned_data.new_alias}}</b> for mailbox <b>{{extra_data.cleaned_data.mailbox}}</b></h3>
    </div>
  </div>
  {% endif %}

  <!-- Successfully delete mailbox alias -->
  {% if extra_data.method == "delete_mailbox_alias" %}
  <div class="row">
    <div class="col col-md-12">
      <h3>You have successfully deleted the alias <b>{{extra_data.cleaned_data.alias}}</b> for mailbox
        <b>{{extra_data.mailbox}}</b></h3>
    </div>
  </div>
  {% endif %}

  {% elif response.error %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col" class="col-md-3">Status</th>
        <th scope="col" class="col-md-9">Message</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="text-danger"><strong>Error</strong></td>
        <td>{{response.error}}</td>
      </tr>
    </tbody>
  </table>
  {% else %}
  {% if response.result|length == 0 %}
  <!-- If Mailbox does not have any aliases -->
  <div class="row">
    <div class="col col-md-12">
      <h3>The mailbox <b>{{extra_data.mailbox}}</b> does not have any aliases</h3>
    </div>
  </div>
  {% else %}
  <!-- Other unexpected errors -->>
  <div class="container">
    <div class="row">
      <div class="col col-md-12 border border-2 rounded-3 p-3 shadow p-3 mb-5 bg-body rounded">
        <p class="text-center text-danger"><strong>{{response}}</strong></p>
      </div>
    </div>
  </div>
  {% endif %}
  {% endif %}
</div>
{% endif %}

<script>
  $(document).ready(function () {
    $('#id_mailbox, #id_alias, #id_old_alias, #id_new_alias').attr('pattern', '[0-9A-Za-z\.]{1,}@[-A-Za-z]{1,}\.{1,2}[-A-Za-z]{2,}$')
  })

  $('button.update-alias').click(function () {
    alias = $(this).attr('alias')
    active_mailbox = $(this).attr('active_mailbox')
    domain_name = active_mailbox.split("@").pop()
    $('.update-alias-form #id_old_alias').val(alias).attr('readonly', 'readonly')
    $('.update-alias-form #id_mailbox').val(active_mailbox)
    $('.update-alias-form #id_domain_name').val(domain_name)
    $('.update-alias-form #id_mailbox, #id_domain_name, #id_old_alias, #id_new_alias').attr('required', true)
  })

  $('button.delete-alias').click(function () {
    alias = $(this).attr('alias')
    active_mailbox = $(this).attr('active_mailbox')
    $('.delete-alias-form #id_alias').val(alias).attr('readonly', 'readonly')
    $('.delete-alias-form #id_active_mailbox').val(active_mailbox)
  })

  $('button.create-alias').click(function () {
    $('.create-alias-form #id_mailbox, #id_domain_name, #id_alias').attr('required', true)
  })

  $('button.get-aliases').click(function () {
    $('.get-aliases-form #id_mailbox').attr('required', true)
  })
</script>
{% endblock %}

apps/stocks_info/templates/toolkit/aliases_service.html
{% extends "stocks_info/home.html" %}

{% block page %}
{{cleaned_data}}
{{response}}

    <form method="post" class="form-inline .was-validated">
    {% csrf_token %}
        <div class="form-group pull-left get-aliases-form">
          {{ form.get_mailbox_aliases }}
          <button class="btn btn-primary get-aliases" type="submit">Get Aliases!</button>
        </div>
    </form>

    <form method="post" class="form-inline .was-validated">
    {% csrf_token %}
        <div class="form-group pull-left get-aliases-form">
          {{ form.create_mailbox_alias }}
          <button class="btn btn-primary get-aliases" type="submit">Create Aliases!</button>
        </div>
    </form>

    <form method="post" class="form-inline .was-validated">
    {% csrf_token %}
        <div class="form-group pull-left get-aliases-form">
          {{ form.update_mailbox_alias }}
          <button class="btn btn-primary get-aliases" type="submit">Update Aliases!</button>
        </div>
    </form>

    <form method="post" class="form-inline .was-validated">
    {% csrf_token %}
        <div class="form-group pull-left get-aliases-form">
          {{ form.delete_mailbox_alias }}
          <button class="btn btn-primary get-aliases" type="submit">Delete Aliases!</button>
        </div>
    </form>

{% endblock %}

apps/stocks_info/templates/toolkit/delete_alias.html
{% extends "stocks_info/home.html" %}

{% block page %}


    <form method="post" class="col-centered form-inline text-center">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-default" type="submit">Delete!</button>
    </form>

{% if alias %}
{{alias}}
{% endif %}

<!--
{% if alias %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col" class="col-md-3">Title</th>
      <th scope="col" class="col-md-9">Result</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Deleted Alias</th>
      <td>{{ alias }}</td>
    </tr>
  </tbody>
</table>
{% endif %}-->
{% endblock %}

apps/stocks_info/templates/toolkit/domain_service.html
{% extends "stocks_info/home.html" %}

{% block page %}
{{cleaned_data}}
{{test_response}}

    <form method="post" class="form-inline .was-validated">
    {% csrf_token %}
        <div class="form-group pull-left get-aliases-form">
          {{ form.create_domain }}
          <button class="btn btn-primary get-aliases" type="submit">Create Domain!</button>
        </div>
    </form>

    <form method="post" class="form-inline .was-validated">
    {% csrf_token %}
        <div class="form-group pull-left get-aliases-form">
          {{ form.get_domain_info }}
          <button class="btn btn-primary get-aliases" type="submit">Get Domain Info!</button>
        </div>
    </form>

    <form method="post" class="form-inline .was-validated">
    {% csrf_token %}
        <div class="form-group pull-left get-aliases-form">
          {{ form.delete_domain }}
          <button class="btn btn-primary get-aliases" type="submit">Delete Domain!</button>
        </div>
    </form>


{% endblock %}

apps/stocks_info/templates/toolkit/get_alias.html
{% extends "stocks_info/home.html" %}

{% block page %}
    <form method="post" class="col-centered form-inline text-center">
        {% csrf_token %}
        <div class="input-group mb-3">
        {{ form.get_mailbox_aliases }}
        <button class="btn btn-primary" type="submit">Get Alias!</button>
        </div>
    </form>
{{method}}
{% if response %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col" class="col-md-3">Title</th>
      <th scope="col" class="col-md-9">Result</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">JSON response</th>
      <td>{{ response }}</td>
    </tr>
    {% if response.result %}
    <tr>
            <th scope="row">Alias:</th>
            <td>{{response.result.0.Alias}}</td>
    </tr>
    <tr>
            <th scope="row">Active:</th>
            <td>{{response.result.0.Active}}</td>
    </tr>
    {% elif response.error %}
        <tr>
            <th scope="row">Error Code:</th>
            <td>{{response.error.code}}</td>
        </tr>
        <tr>
            <th scope="row">Error Message:</th>
            <td>{{response.error.message}}</td>
        </tr>
        <tr>
            <th scope="row">Error Data Type:</th>
            <td>{{response.error.data.type}}</td>
        </tr>
        <tr>
            <th scope="row">Error Data args:</th>
            <td>{{response.error.data.args}}</td>
        </tr>
        <tr>
            <th scope="row">Error Data Message:</th>
            <td>{{response.error.data.message}}</td>
        </tr>
    {% else %}
    <p class="text-center text-danger"><strong>{{response}}</strong></p>
    {% endif %}
  </tbody>
</table>



{% endif %}
{% endblock %}

apps/stocks_info/templates/toolkit/mailbox_service.html
{% extends "stocks_info/home.html" %}

{% block page %}
{{cleaned_data}}
{{test_response}}

    <form method="post" class="form-inline .was-validated">
    {% csrf_token %}
        <div class="form-group pull-left get-aliases-form">
          {{ form.create_mailbox }}
          <button class="btn btn-primary get-aliases" type="submit">Create Mailbox!</button>
        </div>
    </form>

    <form method="post" class="form-inline .was-validated">
    {% csrf_token %}
        <div class="form-group pull-left get-aliases-form">
          {{ form.get_mailbox_info }}
          <button class="btn btn-primary get-aliases" type="submit">Get Mailbox Info!</button>
        </div>
    </form>

    <form method="post" class="form-inline .was-validated">
    {% csrf_token %}
        <div class="form-group pull-left get-aliases-form">
          {{ form.delete_mailbox }}
          <button class="btn btn-primary get-aliases" type="submit">Delete Mailbox!</button>
        </div>
    </form>


{% endblock %}

apps/stocks_info/templates/toolkit/toolkit_facade_main.html
{% extends "stocks_info/home.html" %}

{% block page %}

<div class="text-center col-md-8 align-middle">
    <ul class="list-inline">
        <li class="list-inline-item"><a href="{% url 'domain_service' %}">Domain Service</a></li>
        <li class="list-inline-item"><a href="{% url 'mailbox_service' %}">Mailbox Service</a></li>
        <li class="list-inline-item"><a href="{% url 'aliases_service' %}">Alias Srvice</a></li>
    </ul>
</div>

{% endblock %}